### ISSUE TITLE
ViRogue - Debian packaging

### ISSUE THREAD

**Issue by U039b** [PiRogueToolSuite/project-management#28]
This activity involves:

- the implementation of the generic routing mechanism 
- the integration of Wireguard
- the packaging for Debian

**Comment by U039b** [comment]
**Update:** What you have done so far

**Next month:**  What you plan for the next month

**Challenges:**  What challenges you faced this month

**Comment by CyrilBrulebois** [comment]
#### This month
Packages with hardcoded network-related settings or requirements (interface names, IP address/network, etc.) have been identified and modified to make those configurable. A new `pirogue-admin` tool is being introduced to orchestrate the initial configuration and further modifications in a centralized manner.

#### Next month
The next step is extending `pirogue-admin` so that it can still auto-configure Raspberry Pi 3 and 4 as before, while supporting Eth/Wi-Fi on other devices, as well as a new Eth/Eth mode as well.

#### Challenges
None.

**Comment by U039b** [comment]
#### This month

The initial integration of WireGuard into the `pirogue-networking` and `pirogue-admin` packages happened in August. The `pirogue-networking` side was rather easy as everything was already meant to be as generic as possible in that package, while `pirogue-admin` needed several updates. On one hand, the existing `pirogue-admin` CLI tool was extended to support suggesting VPN mode when autodetection is requested (that happens if the system only reports a single network interface). On the other hand, a new `pirogue-admin-wireguard` CLI tool was introduced to manage all WireGuard-related aspects separately; this includes generating configuration files and/or QR codes to configure the WireGuard application on the target phones.

#### Next month

A few issues were opened to keep track of proposed improvements and cleanup, but VPN support is considered to be feature-complete already.

#### Challenges

None.

**Comment by CyrilBrulebois** [comment]
#### This month

The initial integration of WireGuard into the `pirogue-networking` and `pirogue-admin` packages happened in August. The `pirogue-networking` side was rather easy as everything was already meant to be as generic as possible in that package, while `pirogue-admin` needed several updates. On one hand, the existing `pirogue-admin` CLI tool was extended to support suggesting VPN mode when autodetection is requested (that happens if the system only reports a single network interface). On the other hand, a new `pirogue-admin-wireguard` CLI tool was introduced to manage all WireGuard-related aspects separately; this includes generating configuration files and/or QR codes to configure the WireGuard application on the target phones.

The `pirogue-admin` CLI tool was also extended as scheduled, keeping the ability to auto-configure Raspberry Pi 3 and 4 as before (and also Raspberry Pi 5), in ACCESS POINT mode. Additionally, it can auto-configure WireGuard when running a VM with a single network interface, in VPN mode. Initial support for the APPLIANCE mode is also included (basically when several network interfaces are detected, but none of them is a wireless one).


#### Next month

A few issues were opened to keep track of proposed improvements and cleanup, but VPN support is considered to be feature-complete already.

The APPLIANCE mode needs to be extended to support as many use cases as possible. In this scenario, we expect users to deploy a Debian system on a generic machine, and we want to be able to deal with as many use cases as possible: there are multiple components that can manage the network (e.g. depending on the selected desktop environments) and we're only support `ifupdown` (used in the Debian-provided Raspberry Pi images we modify to generate PTS images) and `systemd-networkd` (used in Debian-provided Cloud images that are available for various cloud providers).


#### Challenges

A number of packages had been modified to fit into a `pirogue-admin`-based configuration. Some concepts were reworked and/or refined to match our needs once those became clearer.

**Comment by CyrilBrulebois** [comment]
#### This month
Many tests were run, using laptops, mixing wired and wireless interfaces, and testing all desktop environments that can be selected from the Debian Installer. Both `pirogue-admin` and `pirogue-networking` were patched to support the various network management tools that can be encountered in those environments, and it was confirmed we could focus on `nftables` only, dropping support for `iptables`.

#### Next month
No more work is scheduled on this topic.

#### Challenges
None.

**Comment by U039b** [comment]
#### This month
All Debian packages have been bumped to version `2.x` and released. They are now available on our [PPA](https://github.com/PiRogueToolSuite/debian-12). Users can now migrade their PiRogues from `v1.x` to this new `2.x` version.

#### Next month
Nothing, as this task is now complete.

#### Challenges
None.
